### ISSUE TITLE
Removing unused step in nightly CICD

### ISSUE THREAD

**Issue by germa89** [ansys/pyfluent-visualization#273]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

The following step is not used in your CICD:

https://github.com/ansys/pyfluent-visualization/blob/d265a34dc9d70328d82fe971d7105149e91412ca/.github/workflows/nightly-doc-build.yml#L22-L28

```yml
      # used for documentation deployment
      - name: Get Bot Application Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.BOT_APPLICATION_ID }}
          application_private_key: ${{ secrets.BOT_APPLICATION_PRIVATE_KEY }}
```

Please remove?

### 📝 Steps to reproduce

NA

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.7

### 📦 Installed packages

```shell
NA
```
